### PR TITLE
Runtime comparisons

### PR DESCRIPTION
**Pull request by mackaiver**
This is what it looks like so far. The makefile performs measurements and produces the plots (if you have all the python stuff installed 😉  )

Storm is not really worth testing at the moment because it become horribly slow for some reason.

eventrate

### CODE REVIEW

**Comment by mackaiver** [comment]
I added another xml. I only enqueue the important events 

```
        <!--Only every 1000nth event will be put into the queue-->
        <streams.DataRate every="1000" logmemory="true"/>
        <Enqueue condition="%{data.@datarate} != null" queue="passDataRate"/>
```

**Comment by alexeyegorov** [comment]
This is what I got with the lastest XML on my macbook using one core (important: also with ``streams-storm``)
bildschirmfoto 2017-03-17 um 14 42 37

**Comment by mackaiver** [comment]
Some things we need to fix I think: 

 - At the moment command line flags are not propagated to the xml it seems. Did you get that working?
 - The one xml file should work for all backends.
 - The storm backend shoudl return errocode 0 when it has processed all items.

**Comment by alexeyegorov** [comment]
I just submitted the most current ``streams-storm`` version, which stops the spout with error code 0.

**Comment by alexeyegorov** [comment]
At the moment, there is a problem with ``queues`` in ``streams-storm``. I am on this, but at least using the *output* attribute combined with a ``Skip`` operator can replace a simple queue with Enqueue. Maybe using this combination for the performance measurement?

**Comment by alexeyegorov** [comment]
``streams-storm`` should now quit the application after all data items have been processed (there was a bug that is now fixed; although, Jenkins seems to be unreachable and the package will be pushed to maven repo ASAP).

**Comment by mackaiver** [comment]
Quite awesome. This works for me now. Calling make automatically compiles, runs and plots everything without problems. I changed the makefile back to renaming the output using a `mv` command. I think we can merge that now. The parameter stuff should still be fixed at some point though. What do you think?.

**Comment by alexeyegorov** [comment]
Gread. Yeah, I need to still fix the parameter stuff. I will open up an issue here and work on it (storm and flink at least).

**Pull request merged**
